
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTc1MTM3MDQ5NiwiZXhwIjoxNzUxNjI5Njk2fQ.Nz6cE6bOsDHyDxkuUb5BPfTropMi1DcwQpBTA1YMe4k

### 📌 Register New User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

### 🔐 Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

### Get all devices (requires token)
GET http://localhost:5000/api/devices
Authorization: {{token}}


### Add new device
POST http://localhost:5000/api/devices
Content-Type: application/json
Authorization: {{token}}

    {
    "name": "AP-52-C10",
    "ip": "172.17.10.52",
    "type": "Access Point",
    "status": 1,
    "description": "Access Point on Crane 10",
    "last_seen": "2025-06-28T11:35:00Z",
    "place": "Crane 10",
    "user_id": 1
    }

### Get a Device by ID
GET http://localhost:5000/api/devices/21
Authorization: {{token}}

### Get a Device by place
GET http://localhost:5000/api/devices/place/Access%20Point
Authorization: {{token}}

### Update a Device by ID
PUT http://localhost:5000/api/devices/25
Authorization: {{token}}
Content-Type: application/json

  {
    "id": 24,
    "name": "AP-52-C10",
    "ip": "172.17.10.51",
    "type": "Access Point",
    "status": 1,
    "description": "Access Point on Crane 10",
    "last_seen": "2025-06-28T11:35:00Z",
    "place": "Access Point",
    "user_id": 1
  }


### DELETE A DEVICE 

DELETE http://localhost:5000/api/devices/16
Authorization: {{token}}
